---
- name: Using the IBM Spectrum Virtualize collection
  collections:
    - ibm.spectrum_virtualize
  gather_facts: no
  connection: local
  hosts: localhost
     tasks:
    - name: Run CLI commands
      register: results
      ibm_svcinfo_command:
        command: "svcinfo lssystem"
        clustername: {{inventory_hostname}}
        log_path: /tmp/test.debug
